name: Pandoc CV

on: push

jobs:
  make_cv_pdf:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p assets/cv
      - uses: docker://pandoc/latex
        with:
          args: >-
            --standalone
            --output=./assets/cv/samantha_barron_cv.pdf
            ./content/cv/cv.md
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./assets/cv